name: test_movie_list
on: workflow_dispatch

env:
  IMAGE_NAME: movie-app-dev

jobs:
  create_docker_images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: build the docker image
        run: docker build . --file Dockerfile.dev --tag $IMAGE_NAME

  # build-push-docker:
  #   runs-on: ubuntu-latest
